// Command publish_dashboard publishes one dashboard into a running Grafana,
// with a real datasource.
//
// Development aid, not part of what users import: the committed JSON carries
// the `${DS_*}` placeholder and an `__inputs` block that asks the importer to
// pick their own datasource, which is exactly what a live server cannot do. So
// this builds the dashboard with a concrete uid instead, drops the two export
// blocks, and overwrites whatever is at that uid, letting the panels be
// exercised against real data before the file is committed.
//
//	GRAFANA_TOKEN=... go run ./cmd/publish_dashboard influxdb <datasource-uid>
//	GRAFANA_TOKEN=... GRAFANA_URL=http://grafana:3000 \
//	    go run ./cmd/publish_dashboard postgres <datasource-uid>
//	GRAFANA_TOKEN=... go run ./cmd/publish_dashboard -loki <loki-uid> influxdb <datasource-uid>
//
// -loki names a Loki datasource on the same server. The exported files carry
// a text panel where the failed job output would be, because an importer may
// have no log store; with the flag the published dashboard draws those lines
// from Loki in that panel's place, same title and same place in the grid.
//
// It writes to a running server, so it refuses to do anything without a token
// and says what it is about to overwrite before it posts.
package main

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"strings"
	"time"

	"github.com/jmrplens/ghchronicle/v2/internal/dashboards"
	"github.com/jmrplens/ghchronicle/v2/internal/grafana"
)

// dsPrefix is what an exported dashboard uses in place of a datasource. Every
// string starting with it is one of those placeholders, wherever it sits.
const dsPrefix = "${DS_"

func main() {
	// Nothing here cancels the run, but the request is posted under one
	// context so that a caller that wanted to could.
	os.Exit(run(context.Background(), os.Args, os.Stdout, os.Stderr))
}

// run is the whole command, with the arguments, the two streams and the exit
// status passed in and handed back rather than taken from the process, so a
// test can drive every way it ends. args[0] is the program name, as in
// os.Args.
func run(ctx context.Context, args []string, stdout, stderr io.Writer) int {
	flags := flag.NewFlagSet(args[0], flag.ContinueOnError)
	flags.SetOutput(stderr)
	loki := flags.String("loki", "", "uid of a Loki datasource: the failed job output panel "+
		"reads the lines from it instead of saying where they went")
	flags.Usage = func() {
		fmt.Fprintf(flags.Output(),
			"usage: %s [-loki <loki-uid>] <store> <datasource-uid>\n\nStores: %s\nGRAFANA_TOKEN is required; GRAFANA_URL defaults to %s.\n",
			args[0], strings.Join(dashboards.Names(), ", "), grafana.DefaultURL)
		flags.PrintDefaults()
	}
	// The statuses a flag.ExitOnError set would exit with: a request for the
	// usage is not a failure, a flag it does not know is.
	if err := flags.Parse(args[1:]); err != nil {
		if errors.Is(err, flag.ErrHelp) {
			return 0
		}
		return 2
	}

	// Both are required. A single argument is the store with its uid
	// forgotten, and taking it as the uid would publish the influxdb
	// dashboard, bound to a datasource named after the store, over whatever
	// is at that uid on a live server.
	if flags.NArg() != 2 {
		flags.Usage()
		return 1
	}
	name, uid := flags.Arg(0), flags.Arg(1)

	store, ok := dashboards.ByName(name)
	if !ok {
		fmt.Fprintf(stderr, "unknown store %q, expected one of %s\n",
			name, strings.Join(dashboards.Names(), ", "))
		return 1
	}

	client := grafana.New()
	// This overwrites a dashboard on a live server, so a missing token has to
	// stop the run rather than produce an anonymous request Grafana may accept.
	if client.Token == "" {
		fmt.Fprintln(stderr, "GRAFANA_TOKEN is not set, refusing to publish")
		return 1
	}

	fmt.Fprintf(stdout, "publishing %s (%s) to %s with datasource %s\n",
		store.Name, store.UID, client.URL, uid)
	if *loki != "" {
		fmt.Fprintf(stdout, "the failed job output panel reads Loki datasource %s\n", *loki)
	}
	res, err := client.Post(ctx, "/api/dashboards/db", map[string]any{
		"dashboard": dashboards.Publishable(store, uid, *loki),
		"overwrite": true,
		"message":   "generated by cmd/publish_dashboard, store " + store.Name,
	}, 60*time.Second)
	if err != nil {
		fmt.Fprintln(stderr, err)
		return 1
	}

	status, _ := res["status"].(string)
	url, _ := res["url"].(string)
	if status != "success" {
		message, _ := res["message"].(string)
		if message == "" {
			message = fmt.Sprint(res)
		}
		fmt.Fprintf(stderr, "%s: %s\n", statusOrUnknown(status), grafana.Trim(message, 200))
		return 1
	}
	fmt.Fprintln(stdout, status, client.URL+url)
	return 0
}

// statusOrUnknown keeps the failure line readable when Grafana answered
// without a status at all.
func statusOrUnknown(status string) string {
	if status == "" {
		return "no status"
	}
	return status
}
