package main

import (
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"strings"
	"sync"
	"testing"

	"github.com/jmrplens/ghchronicle/internal/dashboards"
)

// grafanaStandIn is a Grafana that answers every request with one reply, and
// keeps the bodies it was sent.
type grafanaStandIn struct {
	url    string
	mu     sync.Mutex
	paths  []string
	bodies []map[string]any
}

// serve starts a stand-in answering status and body, and points the command at
// it with a token.
func serve(t *testing.T, status int, body string) *grafanaStandIn {
	t.Helper()
	g := &grafanaStandIn{}
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		raw, err := io.ReadAll(r.Body)
		if err != nil {
			t.Errorf("reading what was posted: %v", err)
		}
		var posted map[string]any
		if err = json.Unmarshal(raw, &posted); err != nil {
			t.Errorf("what was posted is not JSON: %v", err)
		}
		g.mu.Lock()
		g.paths = append(g.paths, r.Method+" "+r.URL.Path)
		g.bodies = append(g.bodies, posted)
		g.mu.Unlock()
		w.WriteHeader(status)
		_, _ = io.WriteString(w, body)
	}))
	t.Cleanup(srv.Close)
	g.url = srv.URL
	t.Setenv("GRAFANA_URL", srv.URL)
	t.Setenv("GRAFANA_TOKEN", "glsa_test")
	return g
}

// requests is how many requests the stand-in has answered.
func (g *grafanaStandIn) requests() int {
	g.mu.Lock()
	defer g.mu.Unlock()
	return len(g.paths)
}

// publish runs the command and returns its status and both streams.
func publish(t *testing.T, args ...string) (status int, stdout, stderr string) {
	t.Helper()
	var out, errOut strings.Builder
	status = run(t.Context(), append([]string{"publish_dashboard"}, args...), &out, &errOut)
	return status, out.String(), errOut.String()
}

// TestPublishOverwritesTheDashboardAtItsUID drives a whole publish: the request
// Grafana is sent, and what the command says about it.
func TestPublishOverwritesTheDashboardAtItsUID(t *testing.T) {
	g := serve(t, http.StatusOK, `{"status":"success","url":"/d/ghchronicle-postgres/x"}`)
	status, stdout, stderr := publish(t, "postgres", "pg-uid")
	if status != 0 {
		t.Fatalf("status %d, stderr %q, want a publish", status, stderr)
	}
	if !strings.Contains(stdout, "publishing postgres (ghchronicle-postgres) to http://") ||
		!strings.Contains(stdout, "with datasource pg-uid") {
		t.Errorf("stdout = %q, want what is about to be overwritten said first", stdout)
	}
	if !strings.HasSuffix(stdout, "success "+g.url+"/d/ghchronicle-postgres/x\n") {
		t.Errorf("stdout = %q, want the status and the dashboard's address", stdout)
	}
	if g.requests() != 1 || g.paths[0] != "POST /api/dashboards/db" {
		t.Fatalf("requests = %v, want one POST to /api/dashboards/db", g.paths)
	}
	body := g.bodies[0]
	if body["overwrite"] != true || body["message"] != "generated by cmd/publish_dashboard, store postgres" {
		t.Errorf("request = %v, want an overwrite that says where it came from", body)
	}
	dashboard, _ := body["dashboard"].(map[string]any)
	if dashboard["uid"] != "ghchronicle-postgres" {
		t.Errorf("dashboard uid = %v, want the store's", dashboard["uid"])
	}
	for _, block := range []string{"__inputs", "__requires"} {
		if _, kept := dashboard[block]; kept {
			t.Errorf("the dashboard still carries %s, which only an importer reads", block)
		}
	}
	raw, err := json.Marshal(dashboard)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(raw), dsPrefix) {
		t.Error("a ${DS_ placeholder survived into the published dashboard")
	}
	if !strings.Contains(string(raw), `{"type":"grafana-postgresql-datasource","uid":"pg-uid"}`) {
		t.Error("no target is bound to the PostgreSQL plugin at the uid given")
	}
}

// TestPublishReportsWhatGrafanaRefused prints Grafana's own reason, or the
// whole reply when it gave none, and fails the run.
func TestPublishReportsWhatGrafanaRefused(t *testing.T) {
	for _, tc := range []struct {
		name, reply, want string
	}{
		{
			"a refusal with a reason", `{"status":"version-mismatch","message":"the dashboard has been changed"}`,
			"version-mismatch: the dashboard has been changed\n",
		},
		{"a reply with no status", `{"id":7}`, "no status: map[id:7]\n"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			serve(t, http.StatusPreconditionFailed, tc.reply)
			status, _, stderr := publish(t, "influxdb", "uid")
			if status != 1 || stderr != tc.want {
				t.Errorf("status %d, stderr %q, want 1 and %q", status, stderr, tc.want)
			}
		})
	}
}

// TestPublishReportsAReplyItCannotRead fails on a reply that is not JSON,
// which is what a proxy in front of Grafana answers with.
func TestPublishReportsAReplyItCannotRead(t *testing.T) {
	serve(t, http.StatusBadGateway, "<html>bad gateway</html>")
	status, _, stderr := publish(t, "influxdb", "uid")
	if status != 1 || !strings.Contains(stderr, "502 Bad Gateway") {
		t.Errorf("status %d, stderr %q, want 1 and the status Grafana's proxy answered", status, stderr)
	}
}

// TestPublishRefusesBeforeTouchingTheServer covers every way the command stops
// without posting: a store it does not know, a missing token, and arguments
// it cannot read.
func TestPublishRefusesBeforeTouchingTheServer(t *testing.T) {
	for _, tc := range []struct {
		name   string
		args   []string
		token  string
		status int
		stderr string
	}{
		{"one argument, the uid forgotten", []string{"influxdb"}, "t", 1, "usage: publish_dashboard [-loki <loki-uid>] <store> <datasource-uid>"},
		{"three arguments", []string{"influxdb", "uid", "extra"}, "t", 1, "Stores: " + strings.Join(dashboards.Names(), ", ")},
		{"a store it does not know", []string{"mysql", "uid"}, "t", 1, `unknown store "mysql", expected one of influxdb`},
		{"no token", []string{"influxdb", "uid"}, "", 1, "GRAFANA_TOKEN is not set, refusing to publish"},
		{"a flag it does not know", []string{"-force", "influxdb", "uid"}, "t", 2, "flag provided but not defined: -force"},
		{"the usage asked for", []string{"-h"}, "t", 0, "GRAFANA_TOKEN is required"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			g := serve(t, http.StatusOK, `{"status":"success"}`)
			t.Setenv("GRAFANA_TOKEN", tc.token)
			status, stdout, stderr := publish(t, tc.args...)
			if status != tc.status || !strings.Contains(stderr, tc.stderr) {
				t.Errorf("status %d, stderr %q, want %d and %q", status, stderr, tc.status, tc.stderr)
			}
			if stdout != "" || g.requests() != 0 {
				t.Errorf("stdout %q after %d requests, want nothing said and nothing posted", stdout, g.requests())
			}
		})
	}
}

// TestLokiFlagSwapsTheNoteForTheLines: without -loki the published dashboard
// keeps the text panel the exported file carries, and with it that one panel
// reads the Loki datasource named, under the same title, and nothing else in
// the document names Loki.
func TestLokiFlagSwapsTheNoteForTheLines(t *testing.T) {
	for _, tc := range []struct {
		name string
		args []string
		kind string
		said bool
	}{
		{"without the flag", []string{"influxdb", "uid"}, "text", false},
		{"with the flag", []string{"-loki", "loki-uid", "influxdb", "uid"}, "logs", true},
	} {
		t.Run(tc.name, func(t *testing.T) {
			g := serve(t, http.StatusOK, `{"status":"success","url":"/d/x"}`)
			status, stdout, stderr := publish(t, tc.args...)
			if status != 0 {
				t.Fatalf("status %d, stderr %q", status, stderr)
			}
			if strings.Contains(stdout, "reads Loki datasource loki-uid") != tc.said {
				t.Errorf("stdout = %q, want the Loki datasource named: %v", stdout, tc.said)
			}
			dashboard, _ := g.bodies[0]["dashboard"].(map[string]any)
			found, lokiPanels := logPanelOf(dashboard)
			if found == nil {
				t.Fatalf("no panel titled %q was posted", logTitle)
			}
			if found["type"] != tc.kind {
				t.Errorf("%q is a %v panel, want %s", logTitle, found["type"], tc.kind)
			}
			if tc.kind == "text" {
				if lokiPanels != 0 {
					t.Errorf("%d panels read Loki, and no Loki was given", lokiPanels)
				}
				return
			}
			if lokiPanels != 1 {
				t.Errorf("%d panels read Loki, want the one", lokiPanels)
			}
			checkLogsPanel(t, found)
		})
	}
}

// logTitle is the panel -loki swaps.
const logTitle = "Where failure output went"

// logPanelOf is the posted panel under logTitle, and how many panels of the
// document read a Loki datasource.
func logPanelOf(dashboard map[string]any) (found map[string]any, lokiPanels int) {
	for _, p := range panelsOf(dashboard["panels"]) {
		if p["title"] == logTitle {
			found = p
		}
		if ds, _ := p["datasource"].(map[string]any); ds["type"] == "loki" {
			lokiPanels++
		}
	}
	return found, lokiPanels
}

// checkLogsPanel holds the swapped panel to the uid the flag named and to
// the sink's stream, filtered by the repository variable.
func checkLogsPanel(t *testing.T, found map[string]any) {
	t.Helper()
	if ds, _ := found["datasource"].(map[string]any); ds["uid"] != "loki-uid" {
		t.Errorf("the logs panel reads %v, want the uid the flag named", found["datasource"])
	}
	targets, _ := found["targets"].([]any)
	if len(targets) != 1 {
		t.Fatalf("%d targets on the logs panel", len(targets))
	}
	target, _ := targets[0].(map[string]any)
	expr, _ := target["expr"].(string)
	if !strings.HasPrefix(expr, `{job="ghchronicle", kind="job_log"}`) || !strings.Contains(expr, `repo=~"$repo"`) {
		t.Errorf("the logs panel reads %q, want the sink's job_log stream filtered by the repository variable", expr)
	}
}

// panelsOf is every panel of a decoded dashboard, rows descended into.
func panelsOf(v any) []map[string]any {
	var out []map[string]any
	list, _ := v.([]any)
	for _, raw := range list {
		p, ok := raw.(map[string]any)
		if !ok {
			continue
		}
		out = append(out, p)
		out = append(out, panelsOf(p["panels"])...)
	}
	return out
}
