#!/bin/sh
# The card gallery under site/src/assets/ is generated by TestCardGallery
# (test/e2e/card_gallery_test.go): one committed SVG per layout in each theme,
# plus a loop pair for the animated layouts, and never hand-edited. The
# layouts page and the README's own pictures read these files directly.
# Nothing enforced that they still match internal/render until this script
# existed: a layout that changed shape without a regeneration looked exactly
# like a clean tree.
#
# This renders the gallery again into a scratch directory and compares it
# against the committed set: same files, no more and no fewer, and every one
# byte-identical. A mismatch names what differs, is missing, or is
# unexpected, and prints the command that fixes it.
set -eu
cd "$(dirname "$0")/.."

ASSETS_DIR="site/src/assets"
# Absolute: `go test` runs with the package directory as its working
# directory, so a relative path would be read against test/e2e/, not here.
REGEN_CMD="GHC_CARD_GALLERY=$(pwd)/$ASSETS_DIR go test ./test/e2e/ -run TestCardGallery -count=1"

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

echo "=== rendering the card gallery into a scratch directory ==="
GHC_CARD_GALLERY="$WORK" go test -count=1 ./test/e2e/ -run TestCardGallery

(cd "$ASSETS_DIR" && for f in card-*.svg; do [ -e "$f" ] && printf '%s\n' "$f"; done) | sort >"$WORK/.committed"
(cd "$WORK" && for f in card-*.svg; do [ -e "$f" ] && printf '%s\n' "$f"; done) | sort >"$WORK/.rendered"

status=0

missing=$(comm -23 "$WORK/.committed" "$WORK/.rendered")
if [ -n "$missing" ]; then
	echo ""
	echo "check-gallery: FAIL: committed but the renderer no longer produces them:"
	printf '%s\n' "$missing" | sed 's/^/  /'
	status=1
fi

extra=$(comm -13 "$WORK/.committed" "$WORK/.rendered")
if [ -n "$extra" ]; then
	echo ""
	echo "check-gallery: FAIL: rendered but not committed:"
	printf '%s\n' "$extra" | sed 's/^/  /'
	status=1
fi

differing=""
for f in $(comm -12 "$WORK/.committed" "$WORK/.rendered"); do
	if ! cmp -s "$ASSETS_DIR/$f" "$WORK/$f"; then
		differing="$differing $f"
	fi
done

if [ -n "$differing" ]; then
	echo ""
	echo "check-gallery: FAIL: no longer matches the renderer:"
	for f in $differing; do
		echo "  $f"
	done
	status=1
fi

if [ "$status" -ne 0 ]; then
	echo ""
	echo "regenerate with:"
	echo "  $REGEN_CMD"
	exit "$status"
fi

count=$(wc -l <"$WORK/.committed" | tr -d ' ')
echo ""
echo "check-gallery: PASS: $count committed cards match the renderer"
