package config

import (
	"encoding/json"
	"fmt"
	"maps"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"slices"
	"strconv"
	"strings"
	"testing"
	"time"
)

// What the configuration builder on the documentation site writes, loaded by
// the parser it writes it for.
//
// The builder is a form, and the author's reason for wanting one was never only
// that a form is easier than an example file: a tool that writes this project's
// configuration is a way to test this project's configuration sideways, by
// loading what it writes. That is this file.
//
// The configurations here are not written here. testdata/config-cases.json is
// generated by site/scripts/gen-config-cases.mjs out of
// site/src/lib/config-build.mjs, which is the module the page's form drives and
// the module that server-renders the page's first output, so what is loaded
// below is what a reader copies off the page rather than a Go reconstruction of
// it. `make check-config-cases` fails when the committed file is no longer what
// that module produces, so either it is regenerated and these tests run the new
// output, or CI stops.

// casesFile is the committed output of the builder, from this package.
var casesFile = filepath.Join("testdata", "config-cases.json")

// builderCases is the whole file.
type builderCases struct {
	// Environment is every variable the cases reference, and the value the
	// loader is expected to resolve it to.
	Environment map[string]string `json:"environment"`
	// Inputs are the composite Action's input names, so a step can be held to
	// what the Action actually reads.
	Inputs []string      `json:"inputs"`
	Cases  []builderCase `json:"cases"`
}

// builderCase is one set of answers and the three things the builder made of
// it: the file, the command that runs the file, and the workflow step.
type builderCase struct {
	Name string `json:"name"`
	Why  string `json:"why"`
	// AllowNoSinks is the waiver -card-only passes, which the builder reads
	// off the answers rather than being told: a configuration that names no
	// destination is refused without it.
	AllowNoSinks bool `json:"allowNoSinks"`
	// Refused is the text the loader is expected to fail with. Empty means
	// the case is expected to load.
	Refused   string            `json:"refused"`
	Answers   map[string]string `json:"answers"`
	Config    string            `json:"config"`
	Run       string            `json:"run"`
	Step      string            `json:"step"`
	NeedsFile bool              `json:"needsFile"`
	// Problems is what the form says is wrong with these answers.
	Problems []builderProblem `json:"problems"`
}

// builderProblem is one thing the form says is wrong with a set of answers.
// Refused means the answer is not in the file at all; warned means it is, and
// the reader is told why it may not be what they wanted.
type builderProblem struct {
	Key  string `json:"key"`
	Kind string `json:"kind"`
}

// problemWith is what the form says about one key, or an empty problem.
func (c builderCase) problemWith(key string) builderProblem {
	for _, problem := range c.Problems {
		if problem.Key == key {
			return problem
		}
	}
	return builderProblem{}
}

// readBuilderCases reads the committed cases, refusing a file with nothing in
// it: a corpus of no cases is a suite that passes over nothing.
func readBuilderCases(t *testing.T) builderCases {
	t.Helper()
	raw, err := os.ReadFile(casesFile)
	if err != nil {
		t.Fatalf("%v. Generate it with `make config-cases`", err)
	}
	var out builderCases
	if err = json.Unmarshal(raw, &out); err != nil {
		t.Fatal(err)
	}
	if len(out.Cases) == 0 {
		t.Fatalf("%s holds no cases, so nothing below proves anything", casesFile)
	}
	return out
}

// TestEveryConfigurationTheBuilderWritesLoads is the claim the whole tool
// rests on. A combination the form allows that the parser refuses is a defect
// in the builder, and it shows here rather than on a reader's first run.
func TestEveryConfigurationTheBuilderWritesLoads(t *testing.T) {
	corpus := readBuilderCases(t)
	for name, value := range corpus.Environment {
		t.Setenv(name, value)
	}
	for _, c := range corpus.Cases {
		t.Run(c.Name, func(t *testing.T) {
			// The one thing a configuration file must never do, whatever the
			// answers: carry a credential. Checked before the load, so it is
			// asked of a file the loader refuses too.
			for key, answer := range c.Answers {
				option := optionNamed(t, key)
				// A map that may carry a credential (an OTLP Authorization
				// header) is marked secret too, and there the reference is
				// inside the value the reader typed rather than instead of
				// it, so it is checked with the other map answers below.
				if option == nil || !option.Secret || option.Kind == KindMap || answer == "" {
					continue
				}
				checkSecretAnswer(t, c, key, answer, corpus.Environment)
			}
			if c.Refused != "" {
				refuseCase(t, c)
				return
			}
			checkAnswers(t, loadCase(t, c), c, corpus.Environment)
		})
	}
}

// variableName is the alphabet ${…} expansion resolves, which is the only
// thing a credential field is allowed to put in a file.
var variableName = regexp.MustCompile(`^[A-Z0-9_]+$`)

// squash is a value with everything but letters and digits dropped and the
// rest upper-cased. It is how "nothing derived from the answer reached the
// file" is asked without asking for one exact spelling of the derivation: the
// fold this test was written for turned a pasted token into
// ${A_PASTED_TOKEN}, which squashes to the same string as the answer.
func squash(s string) string {
	var out strings.Builder
	for _, r := range strings.ToUpper(s) {
		if (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
			out.WriteRune(r)
		}
	}
	return out.String()
}

// checkSecretAnswer holds the file to the promise the page makes about a
// credential field: it takes the NAME of an environment variable, the file
// gets ${NAME}, and the answer's own text never reaches the file.
//
// The assertion this replaced only asked that ${UPPER(answer)} was somewhere
// in the file, which a pasted token satisfies: the emitter folded it into
// ${A_PASTED_TOKEN} and the test agreed the file referenced a variable. The
// question that matters is the other one.
func checkSecretAnswer(t *testing.T, c builderCase, key, answer string, environment map[string]string) {
	t.Helper()
	if value := environment[answer]; value != "" && strings.Contains(c.Config, value) {
		t.Errorf("%s: the file carries the value of %s rather than a reference to it", key, answer)
	}
	if variableName.MatchString(answer) {
		reference := "${" + answer + "}"
		if !strings.Contains(c.Config, reference) {
			t.Errorf("%s: the file does not reference %s", key, reference)
		}
		if strings.Contains(strings.ReplaceAll(c.Config, reference, ""), answer) {
			t.Errorf("%s: the file carries %q outside the reference:\n%s", key, answer, c.Config)
		}
		return
	}
	// Not the name of a variable, so it is not a reference to anything: the
	// file must carry no trace of it, and the form must say so rather than
	// drop the answer in silence.
	if strings.Contains(squash(c.Config), squash(answer)) {
		t.Errorf("%s was answered with something that is not a variable name, and the file still carries it:\n%s", key, c.Config)
	}
	if c.problemWith(key).Kind != "refused" {
		t.Errorf("%s was answered with something that is not a variable name, and the form neither writes it nor says so", key)
	}
}

// refuseCase holds one case the builder can write and the parser refuses. The
// form is a form: a destination is a checkbox and the keys it cannot resolve
// without are not, so a file that dies at start-up is a few clicks away. What
// this asks is that it dies by name.
func refuseCase(t *testing.T, c builderCase) {
	t.Helper()
	path := filepath.Join(t.TempDir(), "config.yaml")
	if err := os.WriteFile(path, []byte(c.Config), 0o600); err != nil {
		t.Fatal(err)
	}
	_, err := LoadWith(path, c.AllowNoSinks)
	if err == nil {
		t.Fatalf("%s\n\nthe builder wrote:\n%s\nand the loader accepted it, though it is expected to refuse it with %q",
			c.Why, c.Config, c.Refused)
	}
	if !strings.Contains(err.Error(), c.Refused) {
		t.Errorf("%s\n\nthe loader refused it with %v, and the page says it says %q", c.Why, err, c.Refused)
	}
}

// loadCase writes one case's configuration where the loader can read it and
// loads it exactly as the run it describes would: -card-only waives the rule
// that a configuration must name a destination, and nothing else does.
func loadCase(t *testing.T, c builderCase) *Config {
	t.Helper()
	path := filepath.Join(t.TempDir(), "config.yaml")
	if err := os.WriteFile(path, []byte(c.Config), 0o600); err != nil {
		t.Fatal(err)
	}
	cfg, err := LoadWith(path, c.AllowNoSinks)
	if err != nil {
		t.Fatalf("%s\n\nthe builder wrote:\n%s\nand the loader refused it: %v", c.Why, c.Config, err)
	}
	return cfg
}

// checkAnswers holds the loaded configuration to every answer that produced
// it, key by key, so the test says the file means what the reader asked for
// rather than only that it parses.
func checkAnswers(t *testing.T, cfg *Config, c builderCase, environment map[string]string) {
	t.Helper()
	var checked int
	for _, key := range slices.Sorted(maps.Keys(c.Answers)) {
		answer := c.Answers[key]
		if strings.TrimSpace(answer) == "" {
			continue // the form's way of saying "leave the default alone"
		}
		if c.problemWith(key).Kind == "refused" {
			// An answer the form refused to write. It is not in the file, and
			// checkSecretAnswer has already held it to that; holding the
			// loaded configuration to it too would be asking the file to
			// carry what the page says it never carries.
			continue
		}
		if checkAnswer(t, cfg, key, answer, environment) {
			checked++
		}
	}
	if checked == 0 {
		t.Errorf("%s: not one answer was checked against the loaded configuration", c.Name)
	}
}

// checkAnswer holds one answer to the loaded configuration, and says whether
// it checked anything.
func checkAnswer(t *testing.T, cfg *Config, key, answer string, environment map[string]string) bool {
	t.Helper()
	// A group chosen by name. The selection is not a field: it is what the
	// sweep narrows to, which is what Selection reports.
	if group, chose := strings.CutPrefix(key, "groups."); chose {
		on, _, narrowed := cfg.Selection()
		if !narrowed || !slices.Contains(on, group) {
			t.Errorf("groups names %s and the configuration collects for %v (narrowed %v)", group, on, narrowed)
		}
		return true
	}
	// A cadence for one family. The map entry is checked through the schedule
	// rather than only as text, because a family's interval reaching the
	// runner is the whole point of the every block, and the nested form is
	// exactly what the flat one failed to do.
	if family, named := strings.CutPrefix(key, "every.families."); named {
		want, err := time.ParseDuration(answer)
		if err != nil {
			t.Errorf("every.families.%s was answered %q, which is not a duration", family, answer)
			return true
		}
		got, enabled := cfg.Interval(family)
		if !enabled || got != want {
			t.Errorf("every.families.%s asked for %s and the family resolves to %s (enabled %v)",
				family, want, got, enabled)
		}
		return true
	}
	// A cadence for a whole group, which is a map entry and not a field: what
	// it does to each family is the layer resolution's business, covered by
	// cadences_test.go, and what the builder has to get right is that the
	// entry reaches the right layer.
	if _, named := strings.CutPrefix(key, "every.groups."); named {
		got, found := valueAt(cfg, key)
		if !found || got != answer {
			t.Errorf("%s was answered %q and the loaded configuration holds %q (found %v)", key, answer, got, found)
		}
		return true
	}
	option := optionNamed(t, key)
	if option == nil {
		t.Errorf("%s is answered and is not a setting the binary has", key)
		return true
	}
	if option.Kind == KindBlock {
		// A sink switched on has to reach the loader as a sink. A bare key
		// decodes as null and leaves the pointer nil, which is the sink not
		// being there at all.
		if value, found := valueAt(cfg, key); found && value == "nil" {
			t.Errorf("%s was switched on and the loaded configuration has no such sink", key)
		}
		return true
	}
	want := answer
	switch {
	case option.Kind == KindMap:
		// The loader expands ${VAR} inside a header's value, so the answer is
		// expanded the same way before it is compared: that expansion is the
		// whole reason a credential can be referenced from a header at all.
		want = expandRefs(answer, environment)
	case option.Secret:
		want = environment[strings.ToUpper(answer)]
		if want == "" {
			t.Errorf("%s references %s, which the cases file gives no value", key, answer)
			return true
		}
	}
	got, found := valueAt(cfg, key)
	if !found {
		t.Errorf("%s is answered and the loaded configuration has no such field", key)
		return true
	}
	if got != want {
		t.Errorf("%s was answered %q and the loaded configuration holds %q", key, want, got)
	}
	return true
}

// optionNamed is one setting by key, or nil.
func optionNamed(t *testing.T, key string) *Option {
	t.Helper()
	options, err := Options()
	if err != nil {
		t.Fatal(err)
	}
	i := slices.IndexFunc(options, func(o Option) bool { return o.Key == key })
	if i < 0 {
		return nil
	}
	return &options[i]
}

// valueAt reads one setting out of a loaded configuration by its dotted key,
// as text, and says whether the path reached a field at all.
//
// By reflection over the same yaml tags the loader decodes with, so the test
// needs no ladder of accessors and a setting added is checked the day it is
// answered. A nil pointer answers "nil", which is how a sink that did not
// reach the loader is told from one that did.
func valueAt(cfg *Config, key string) (string, bool) {
	v := reflect.ValueOf(cfg).Elem()
	for part := range strings.SplitSeq(key, ".") {
		for v.Kind() == reflect.Pointer {
			if v.IsNil() {
				return "nil", true
			}
			v = v.Elem()
		}
		if v.Kind() == reflect.Map {
			entry := v.MapIndex(reflect.ValueOf(part))
			if !entry.IsValid() {
				return "", false
			}
			v = entry
			continue
		}
		if v.Kind() != reflect.Struct {
			return "", false
		}
		field, found := fieldNamed(v, part)
		if !found {
			return "", false
		}
		v = field
	}
	for v.Kind() == reflect.Pointer {
		if v.IsNil() {
			return "nil", true
		}
		v = v.Elem()
	}
	return text(v), true
}

// fieldNamed is the field one yaml key names, in a struct value.
func fieldNamed(v reflect.Value, name string) (reflect.Value, bool) {
	t := v.Type()
	for i := range t.NumField() {
		tag, _, _ := strings.Cut(t.Field(i).Tag.Get("yaml"), ",")
		if tag == name {
			return v.Field(i), true
		}
	}
	return reflect.Value{}, false
}

// text renders one loaded value the way the form's answer is written, so the
// two can be compared: a list as the comma separated list the control holds, a
// number and a boolean as themselves.
func text(v reflect.Value) string {
	switch v.Kind() {
	case reflect.String:
		return v.String()
	case reflect.Bool:
		return strconv.FormatBool(v.Bool())
	case reflect.Int, reflect.Int64:
		return strconv.FormatInt(v.Int(), 10)
	case reflect.Slice:
		out := make([]string, v.Len())
		for i := range v.Len() {
			out[i] = fmt.Sprint(v.Index(i).Interface())
		}
		return strings.Join(out, ", ")
	case reflect.Map:
		// One pair a line, sorted, which is how the form's control holds the
		// same setting and how the file writes it.
		keys := make([]string, 0, v.Len())
		for _, key := range v.MapKeys() {
			keys = append(keys, key.String())
		}
		slices.Sort(keys)
		out := make([]string, 0, len(keys))
		for _, key := range keys {
			out = append(out, fmt.Sprintf("%s: %v", key, v.MapIndex(reflect.ValueOf(key)).Interface()))
		}
		return strings.Join(out, "\n")
	default:
		return fmt.Sprint(v.Interface())
	}
}

// expandRefs resolves the ${VAR} references in a value the way the loader
// does, so an answer carrying one can be compared with what was loaded.
func expandRefs(text string, environment map[string]string) string {
	for name, value := range environment {
		text = strings.ReplaceAll(text, "${"+name+"}", value)
	}
	return text
}

// TestTheCadencesTheBuilderWritesAreTheNestedForm is the shape that has bitten
// this project hardest: the flat every block is fatal, and the loader carries
// a migration hint for a file that still has one. A builder that wrote the old
// shape would produce a file that cannot start, so the case that answers
// cadences is read as text as well as loaded.
func TestTheCadencesTheBuilderWritesAreTheNestedForm(t *testing.T) {
	corpus := readBuilderCases(t)
	var found int
	for _, c := range corpus.Cases {
		if !strings.Contains(c.Config, "\nevery:\n") {
			continue
		}
		found++
		for _, family := range Families() {
			flat := "\n  " + family + ":"
			if strings.Contains(configBlock(c.Config, "every"), flat) {
				t.Errorf("%s: writes %s directly under every, which is the flat form the loader refuses", c.Name, family)
			}
		}
		if !strings.Contains(c.Config, "\n  families:\n") {
			t.Errorf("%s: has an every block with no families layer", c.Name)
		}
	}
	if found == 0 {
		t.Fatal("no case answers a cadence, so the form that has bitten twice is not covered")
	}
}

// configBlock is one top-level block of a configuration, as text: from its key
// to the next line that starts in the first column.
func configBlock(body, key string) string {
	_, rest, found := strings.Cut(body, "\n"+key+":\n")
	if !found {
		return ""
	}
	var out strings.Builder
	for line := range strings.SplitSeq(rest, "\n") {
		if line != "" && !strings.HasPrefix(line, " ") {
			break
		}
		out.WriteString("\n" + line)
	}
	return out.String()
}

// TestEveryStepTheBuilderWritesUsesInputsTheActionDeclares holds the second
// output to the Action it is a step of. An input the Action does not read is a
// line that silently does nothing, and the token must never be a value.
func TestEveryStepTheBuilderWritesUsesInputsTheActionDeclares(t *testing.T) {
	corpus := readBuilderCases(t)
	if len(corpus.Inputs) == 0 {
		t.Fatal("the cases file carries no Action inputs, so nothing below is checked")
	}
	var withFile, withoutFile int
	for _, c := range corpus.Cases {
		for line := range strings.SplitSeq(c.Step, "\n") {
			key, _, isPair := strings.Cut(strings.TrimSpace(line), ":")
			if !isPair || !strings.HasPrefix(line, "    ") {
				continue
			}
			if !slices.Contains(corpus.Inputs, key) {
				t.Errorf("%s: the step sets %q, which the Action does not declare", c.Name, key)
			}
		}
		if strings.Contains(c.Step, "token: ${{ secrets.") == false {
			t.Errorf("%s: the step does not take its token from a secret", c.Name)
		}
		// A step that needs a file must name one, and a step that needs none
		// must not: the Action builds its own configuration only when no
		// config input is given, so a file beside user and include-private
		// would be two answers the Action never reads.
		if got := strings.Contains(c.Step, "config:"); got != c.NeedsFile {
			t.Errorf("%s: the step names a config file %v, and the answers need one %v", c.Name, got, c.NeedsFile)
		}
		checkStepStarts(t, c)
		if c.NeedsFile {
			withFile++
		} else {
			withoutFile++
		}
	}
	if withFile == 0 || withoutFile == 0 {
		t.Errorf("the cases cover %d steps with a file and %d without; both shapes need one", withFile, withoutFile)
	}
}

// checkStepStarts is the question the shape of a step never answered: would
// the run it describes start at all.
//
// A configuration that names no destination is refused, and the Action waives
// that in exactly one place: `mode: card` with a `card:` path becomes
// -card-only in scripts/action-run.sh. So a step for answers that send the
// points nowhere has to be a card run with somewhere to put the card, and a
// step for answers that name a destination must not be, because `mode: card`
// with no card path is refused by the Action's own script.
func checkStepStarts(t *testing.T, c builderCase) {
	t.Helper()
	card := strings.Contains(c.Step, "\n    mode: card")
	if card != c.AllowNoSinks {
		t.Errorf("%s: the step is a card run %v, and the answers name no destination %v. %s",
			c.Name, card, c.AllowNoSinks, c.Step)
	}
	if card && !strings.Contains(c.Step, "\n    card: ") {
		t.Errorf("%s: the step asks for mode card and names no card, which the Action refuses with "+
			"\"mode card needs a card path\":\n%s", c.Name, c.Step)
	}
}

// TestTheCommandTheBuilderPrintsRunsTheFileBesideIt holds the third output to
// the first. The page prints one command per set of answers, and for a
// configuration that names no destination it cannot be the plain sweep: -once
// is refused at start-up, by a parser asking for a sink the reader
// deliberately did not want. -card-only is the one run that waives the rule,
// and the flag that waives it is the flag the case is loaded with above.
func TestTheCommandTheBuilderPrintsRunsTheFileBesideIt(t *testing.T) {
	corpus := readBuilderCases(t)
	for _, c := range corpus.Cases {
		if c.Run == "" {
			t.Errorf("%s: no command at all, so the page tells a reader nothing to do with the file", c.Name)
			continue
		}
		if got := strings.Contains(c.Run, "-card-only"); got != c.AllowNoSinks {
			t.Errorf("%s: the command waives the sink rule %v, and the file needs it waived %v: %s",
				c.Name, got, c.AllowNoSinks, c.Run)
		}
		if c.AllowNoSinks && !strings.Contains(c.Run, "-card ") {
			t.Errorf("%s: -card-only with no card writes nothing at all: %s", c.Name, c.Run)
		}
	}
}

// TestTheShapesThatHaveBittenAreCovered pins the corpus itself. The cases are
// the reason this file exists, and a case quietly dropped would leave every
// test above passing over a smaller corpus.
func TestTheShapesThatHaveBittenAreCovered(t *testing.T) {
	corpus := readBuilderCases(t)
	var nested, private, secret, cardOnly, refused, pasted, warned, emptyList bool
	for _, c := range corpus.Cases {
		nested = nested || strings.Contains(c.Config, "\n  families:\n")
		private = private || strings.Contains(c.Config, "include_private:")
		secret = secret || strings.Contains(c.Config, "${INFLUX_TOKEN}")
		cardOnly = cardOnly || c.AllowNoSinks
		refused = refused || c.Refused != ""
		emptyList = emptyList || c.Answers["targets.orgs"] == " , , "
		for _, problem := range c.Problems {
			pasted = pasted || problem.Kind == "refused"
			warned = warned || problem.Kind == "warned"
		}
	}
	for _, covered := range []struct {
		shape string
		is    bool
	}{
		{"a cadence under every.families", nested},
		{"include_private", private},
		{"a sink whose credentials are ${VAR} references", secret},
		{"a card-only configuration, with no sink at all", cardOnly},
		{"a configuration the parser refuses, so the refusal is held to its own words", refused},
		{"a credential field answered with the credential, which the form refuses to write", pasted},
		{"an answer the form writes and warns about", warned},
		{"a list answered with nothing but separators", emptyList},
	} {
		if !covered.is {
			t.Errorf("no case covers %s; see CASES in site/scripts/gen-config-cases.mjs", covered.shape)
		}
	}
}
